### ISSUE TITLE
jp mem16 throws "invalid operand $36e0 !"

### ISSUE THREAD

**Issue by ISSOtm** [ISSOtm/gbz80-to-items#6]
Seems to come from wrong label parsing.

**Comment by ISSOtm** [comment]
Same thing happens with `jr`.

**Comment by joefarebrother** [comment]
I think it's because of [this line](https://github.com/ISSOtm/gbz80-to-items/blob/master/compiler.js#L577), which checks if the operand is a string. But it's ALWAYS a string, so it will always be interpreted as a jump to a label. But no label exists called "$36e0".

A possible fix would be to wrap a try/catch around readWord(), and only treat it as a label if it throws due to not being able to parse it as a word.

Also, maybe changing the error message to "invalid label" or something might be clearer than "invalid operand"

**Comment by ISSOtm** [comment]
Changed in 5756aa2c784caf15dc2bb2385916dc9137c7e02d.
When the compiler is sure the operand is a label, it throws an appropriate error instead of the generic "operand" one.
Applied a fix similar to the one you proposed, but a little different.
